name: Fast Zero CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | sh
          echo "POETRY_VIRTUALENVS_PATH=$HOME/.poetry/env" >> $GITHUB_ENV
          echo "POETRY_ACTIVE=1" >> $GITHUB_ENV
          source $HOME/.poetry/env

      - name: Install dependencies
        run: |
          poetry install

      - name: Run lint
        run: |
          poetry run task lint

      - name: Run tests
        run: |
          poetry run task test
